# POLI operator and image locaters
# comma delimited
# do not mix network and local locaters on suite line

[operator_suites]
all= ${POLI_HOME}/packages/all
avhrr= ${POLI_HOME}/packages/avhrr
basic= ${POLI_HOME}/packages/starter, ${POLI_HOME}/packages/edge, ${POLI_HOME}/packages/thresh
morph= ${POLI_HOME}/packages/morph
sinks= ${POLI_HOME}/packages/sinks
sources= ${POLI_HOME}/packages/sources
urlops= ${POLI_URL}/operators/URLmisc, ${POLI_URL}/operators/URLsame
som= ${POLI_HOME}/packages/et_som, ${POLI_HOME}/packages/starter
#wrf= ${POLI_HOME}/packages/et_som

[data_suites]
gen_im= ${POLI_HOME}/data/general
agrineer= ${POLI_URL}/data/URLgeneral, ${POLI_URL}/data/URLml, ${POLI_URL}/data/URLsat, ${POLI_URL}/data/URLwrf
numpy= ${POLI_HOME}/data/ml
netcdf= ${POLI_HOME}/data/wrf_2022
sat= ${POLI_HOME}/data/avhrr, ${POLI_HOME}/data/modis

