# POLI operator and image locaters
# comma delimited
# do not mix network and local locaters on suite line

[operator_suites]
basic: /study/ecuador/poli/packages/starter, /study/ecuador/poli/packages/et_som 
som: /study/ecuador/poli/packages/et_som, /study/ecuador/poli/packages/starter
test: /study/ecuador/poli/packages/et_som
agrineer: https://www.agrineer.org/publish/operators/URLmisc, https://www.agrineer.org/publish/operators/URLsame
same: https://www.agrineer.org/publish/operators/URLmisc

[data_suites]
gen_im: /study/ecuador/poli/data/general
agrineer: https://www.agrineer.org/publish/images/URLgeneral, https://www.agrineer.org/publish/images/URLtest
