# POLI operator and image locaters
# comma delimited
# do not mix network and local locaters on suite line

# satellite package
[operator_suites]
noaa= ${POLI_HOME}/packages/avhrr
modis= ${POLI_HOME}/packages/modis_src, ${POLI_HOME}/packages/modis_ops

[data_suites]
avhrr= ${POLI_HOME}/data/avhrr
modis= ${POLI_HOME}/data/modis
